name: CD

on: 
  push:
    branches: [ notesapp-consumer ]

jobs:
  deploy:
    name: Deploy and Run Jest Test
    environment: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To AWS EC2 Server Using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/local/bin
            cd /home/ilham/projects/devops-exercise
            git pull origin notesapp-consumer
            git status
            npm ci
            npm run test
            pm2 restart notesapp-consumer
