name: CD

on:
  push:
    branches: [notesapp-consumer]

jobs:
  test:
    name: Run Tests
    environment: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Run Jest Tests on AWS EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/local/bin
            cd /home/ilham/projects/devops-exercise
            git pull origin notesapp-consumer
            git status
            npm ci
            npm run lint
            npm run test

  deploy:
    name: Deploy Application
    environment: AWS
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Deploy To AWS EC2 Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/local/bin
            cd /home/ilham/projects/devops-exercise
            pm2 restart notesapp-consumer
